name = "doric-paint-finishes"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_directory = ".next"

[site]
bucket = ".next"
entry-point = "."

[env.production]
workers_dev = true

[pages]
pages_build_output_dir = ".vercel/output/static" 